french_contractions = {
    "au": "à le",
    "aux": "à les",
    "du": "de le",
    "des": "de les",
    "ce": "cet",
    "ces": "ces",
    "cet": "ce",
    "cette": "ce",
    "J'ai":'Je ai',
    "C'est" : 'Ce est',
    "depuis": "depuis",
    "jusqu'au": "jusqu'à le",
    "jusqu'à": "jusqu'à",
    "jusqu'aux": "jusqu'à les",
    "lorsque": "lorsque",
    "parce que": "parce que",
    "puisqu'il": "puisqu'il",
    "puisqu'elle": "puisqu'elle",
    "puisqu'on": "puisqu'on",
    "quel": "quel",
    "quelle": "quelle",
    "quelles": "quelles",
    "quels": "quels",
    "sans que": "sans que",
    "vers le": "vers le",
    "vers la": "vers la",
    "vers les": "vers les",
    "vers": "vers",
    "entre le": "entre le",
    "entre la": "entre la",
    "entre les": "entre les",
    "entre": "entre",
    "dans le": "dans le",
    "dans la": "dans la",
    "dans les": "dans les",
    "dans": "dans",
    "devant le": "devant le",
    "devant la": "devant la",
    "devant les": "devant les",
    "devant": "devant",
    "sous le": "sous le",
    "sous la": "sous la",
    "sous les": "sous les",
    "sous": "sous",
    "sur le": "sur le",
    "sur la": "sur la",
    "sur les": "sur les",
    "sur": "sur",
    "près de": "près de",
    "près": "près",
    "par le": "par le",
    "par la": "par la",
    "par les": "par les",
    "par": "par",
    "avec le": "avec le",
    "avec la": "avec la",
    "avec les": "avec les",
    "avec": "avec",
    "d'un": "de un",
    "d'une": "de une",
    "d'un": "de un",
    "d'une": "de une",
    "d'un": "de un",
    "d'une": "de une",
    "d'un": "de un",
    "d'une": "de une",
    "d'aller" : "de aller",
    "c'est": "ce est",
    "c'était": "ce était",
    "ceci": "ceci",
    "cela": "cela",
    "ça": "ça",
    "qu'est-ce que": "qu'est-ce que",
    "quelqu'un": "quelqu'un",
    "quelqu'une": "quelqu'une",
    "quels sont": "quels sont",
    "quelles sont": "quelles sont",
    "quoi": "quoi",
    "comme": "comme",
    "que": "que",
    "que": "que",
    "qui": "qui",
    "qui": "qui",
    "qu'il": "qu'il",
    "qu'elle": "qu'elle",
    "qu'on": "qu'on",
    "qu'ils": "qu'ils",
    "qu'elles": "qu'elles",
    "qu'on": "qu'on"
}