italian_contractions = {
    "nel": "in il",
    "nella": "in la",
    "nei": "in i",
    "nelle": "in le",
    "sul": "su il",
    "sulla": "su la",
    "sui": "su i",
    "sulle": "su le",
    "allo": "a lo",
    "alla": "a la",
    "alle": "a le",
    "ai": "a i",
    "agli": "a gli",
    "dagli": "da gli",
    "aglielo": "a glielo",
    "aglieli": "a glieli",
    "agliela": "a gliela",
    "aglieli": "a glieli",
    "agliene": "a gliene",
    "dal": "da il",
    "dalla": "da la",
    "dai": "da i",
    "dalle": "da le",
    "dello": "di lo",
    "della": "di la",
    "delli": "di i",
    "delle": "di le",
    "nel": "ne il",
    "nello": "ne lo",
    "nell": "ne le",
    "nella": "ne la",
    "nei": "ne i",
    "nello": "ne lo",
    "nei": "ne i",
    "negli": "ne gli",
    "nelle": "ne le",
    "negli": "ne gli",
    "nele": "ne le",
    "sul": "su il",
    "sullo": "su lo",
    "sul": "su il",
    "sugli": "su gli",
    "sulla": "su la",
    "sulle": "su le",
    "sui": "su i",
    "sugli": "su gli",
    "suglielo": "su glielo",
    "suglieli": "su glieli",
    "sugliela": "su gliela",
    "suglieli": "su glieli",
    "sugliene": "su gliene",
    "col": "con il",
    "coi": "con i",
    "conlo": "con lo",
    "colli": "con li",
    "colla": "con la",
    "cole": "con le",
    "sotto": "sotto",
    "su": "su",
    "tra": "tra",
    "fra": "fra",
    "contro": "contro",
    "lontano": "lontano",
    "vicino": "vicino",
    "dopo": "dopo",
    "prima": "prima",
    "fuori": "fuori",
    "dentro": "dentro",
    "dietro": "dietro",
    "quando": "quando",
    "mentre": "mentre",
    "se": "se",
    "perché": "perché",
    "perche": "perché",
    "quanto": "quanto",
    "come": "come",
    "da": "da",
    "di": "di",
    "in": "in",
    "con": "con",
    "su": "su",
    "per": "per",
    "tra": "tra",
    "fra": "fra",
    "e": "e",
    "o": "o",
    "ma": "ma",
    "ne": "ne",
    "solo": "solo",
    "sol": "solo",
    "così": "così",
    "ancora": "ancora",
    "senza": "senza",
    "tutto": "tutto",
    "tutti": "tutti",
    "tutta": "tutta",
    "tutte": "tutte",
    "anche": "anche",
    "sia": "sia",
    "siano": "siano",
    "fosse": "fosse",
    "fossero": "fossero",
    "dunque": "dunque",
    "però": "però",
    "perciò": "perciò",
    "infatti": "infatti",
    "pure": "pure",
    "anche": "anche",
    "infine": "infine",
    "pure": "pure",
    "quasi": "quasi",
    "soprattutto": "soprattutto",
    "ovunque": "ovunque",
    "veramente": "veramente",
    "praticamente": "praticamente",
    "possibile": "possibile",
    "probabile": "probabile",
    "probabilmente": "probabilmente",
    "pericoloso": "pericoloso",
    "serio": "serio",
    "sicuro": "sicuro",
    "forte": "forte",
    "vicino": "vicino",
    "lontano": "lontano",
    "povero": "povero",
    "ricco": "ricco",
    "meglio": "meglio",
    "peggio": "peggio",
    "di": "di",
    "più": "più",
    "meno": "meno",
    "sopra": "sopra",
    "sotto": "sotto",
    "verso": "verso",
    "intorno": "intorno",
    "insieme": "insieme",
    "nemico": "nemico",
    "amico": "amico",
    "vecchio": "vecchio",
    "nuovo": "nuovo",
    "giovane": "giovane",
    "vecchi": "vecchi",
    "nuovi": "nuovi",
    "giovani": "giovani",
    "alto": "alto",
    "basso": "basso",
    "lungo": "lungo",
    "corto": "corto",
    "largo": "largo",
    "stretto": "stretto",
    "pieno": "pieno",
    "vuoto": "vuoto",
    "luminoso": "luminoso",
    "buio": "buio",
    "bello": "bello",
    "brutto": "brutto",
    "sano": "sano",
    "malato": "malato",
    "caldo": "caldo",
    "freddo": "freddo",
    "dolce": "dolce",
    "amaro": "amaro",
    "grosso": "grosso",
    "piccolo": "piccolo",
    "pesante": "pesante",
    "leggero": "leggero",
    "lungo": "lungo",
    "corto": "corto",
    "nuovo": "nuovo",
    "vecchio": "vecchio",
    "buono": "buono",
    "cattivo": "cattivo",
    "bel": "bel",
    "bravo": "bravo",
    "malo": "malo",
    "felice": "felice",
    "triste": "triste",
    "ricco": "ricco",
    "povero": "povero",
    "forte": "forte",
    "debole": "debole",
    "bello": "bello",
    "lontano": "lontano",
    "vicino": "vicino",
    "aperto": "aperto",
    "chiuso": "chiuso",
    "verde": "verde",
    "rosso": "rosso",
    "giallo": "giallo",
    "blu": "blu",
    "bianco": "bianco",
    "nero": "nero",
    "grigio": "grigio",
    "rosa": "rosa",
    "arancione": "arancione",
    "viola": "viola",
    "marrone": "marrone"}