spanish_contractions = {
    "al": "a el",
    "del": "de el",
    "conmigo": "con mí",
    "contigo": "con ti",
    "consigo": "con sí",
    "verlo": "ver lo",
    "mostrármela": "mostrar me la",
    "ayúdame": "ayuda me",
    "váyase": "vaya se",
    "haciéndolo": "haciendo lo",
    "hablándote": "hablando te",
    "a": "a",
    "de": "de",
    "la": "la",
    "los": "los",
    "las": "las",
    "mí": "mí",
    "ti": "ti",
    "sí": "sí",
    "estar": "estar",
    "estás": "estás",
    "estoy": "estoy",
    "estábamos": "estábamos",
    "ser": "ser",
    "eres": "eres",
    "es": "es",
    "somos": "somos",
    "sois": "sois",
    "son": "son",
    "fui": "fui",
    "fuiste": "fuiste",
    "fue": "fue",
    "fuimos": "fuimos",
    "fuisteis": "fuisteis",
    "fueron": "fueron",
    "seré": "seré",
    "serás": "serás",
    "será": "será",
    "seremos": "seremos",
    "seréis": "seréis",
    "serán": "serán",
    "sería": "sería",
    "serías": "serías",
    "seríamos": "seríamos",
    "seríais": "seríais",
    "serían": "serían",
    "era": "era",
    "eras": "eras",
    "éramos": "éramos",
    "erais": "erais",
    "eran": "eran",
    "seas": "seas",
    "seamos": "seamos",
    "seáis": "seáis",
    "sean": "sean",
    "fuera": "fuera",
    "fueras": "fueras",
    "fuéramos": "fuéramos",
    "fuerais": "fuerais",
    "fueran": "fueran",
    "fuese": "fuese",
    "fueses": "fueses",
    "fuésemos": "fuésemos",
    "fueseis": "fueseis",
    "fuesen": "fuesen",
    "siento": "siento",
    "sientes": "sientes",
    "siente": "siente",
    "sentimos": "sentimos",
    "sentís": "sentís",
    "sienten": "sienten",
    "sentí": "sentí",
    "sentiste": "sentiste",
    "sintió": "sintió",
    "sintieron": "sintieron",
    "sintiera": "sintiera",
    "sintieras": "sintieras",
    "sintiéramos": "sintiéramos",
    "sintierais": "sintierais",
    "sintieran": "sintieran",
    "sintiese": "sintiese",
    "sintieses": "sintieses",
    "sintiésemos": "sintiésemos",
    "sintieseis": "sintieseis",
    "sintiesen": "sintiesen",
    "sintiendo": "sintiendo",
    "sentido": "sentido",
    "sentida": "sentida",
    "sentidos": "sentidos",
    "sentidas": "sentidas",
    "siente": "siente",
    "sienta": "sienta",
    "sintamos": "sintamos",
    "sintáis": "sintáis",
    "sientan": "sientan",
}